global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ilya_kudryashov'
