version: '3.3'

services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit

  ui:
    image: ${USER_NAME}/ui:${VERSION_APP}
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post
    networks:
      - reddit
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${VERSION_APP}
    networks:
      - reddit

  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      - reddit
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
