version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    networks:
      - logging
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.4.0
    networks:
      - logging
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.4.0
    networks:
      - logging
    ports:
      - "5601:5601"

networks:
  logging:
